version : "3"
services:
  app:
    container_name: css-yt-scrapper
    restart: unless-stopped
    build: .
    ports:
      - '3401:3401'
    links:
      - mongo 
    environment:
      - DB_HOST=mongodb://mongo/ytDocuments
      - PORT=3401
      - NODE_ENV=Development 
    networks:
      - app-network
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules      
  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped       
    ports:
      - '27018:27017'
    networks:
      - app-network
    volumes:
      - dbdata:/data/db
volumes:
  dbdata:
  node_modules:                    
networks:
  app-network:
    driver: bridge      
    